@api = http://127.0.0.1:5000

GET {{api}}

###agregar
POST {{api}}/users
Content-Type: application/json

{
    "nombre": "Eddy",
    "username": "Eddy12@",
    "rol":1,
    "password": "eddy1234"
}

####
PUT {{api}}/user/6559a09915920629054dcef4
Content-Type: application/json

{
    "nombre": "Juan Bolas",
    "username": "Juan69",
    "rol":1
}


###agregar
POST {{api}}/login
Content-Type: application/json

{
    "username": "Eddy12@",
    "password": "eddy1234"
}
####
GET {{api}}/users
Content-Type: application/json

####
GET {{api}}/username/Juan69
Content-Type: application/json

###
GET {{api}}/user/652de98ff8092df48bc0e366
Content-Type: application/json

###
DELETE {{api}}/user/652e1a0d897677ef29e6e73c
Content-Type: application/json


####
POST {{api}}/pc
Content-Type: application/json

{
    "Codigo": "PC-93075-B",
    "Marca": "DELL",
    "SistemaOperativo": "Windows 10 Pro1234",
    "Hardware": [
        "intel i3 10ma",
        "4GB RAM",
        "1 TB De almacenamiento"
    ],
    "Software": [
        "Office 365",
        "Microsoft Edge",
        "B-View"
    ],
    "Actualizaciones": "Últimas actualizaciones",
    "Configuración Red": "sin epecificar",
    "Usuarios": "Usuarios: 1",
    "Seguridad": "Contraseñas Baja",
    "RegistroEventos": "Monitoreado",
    "Microscopio": {
        "Codigo": "MC-93075-A",
        "Modelo": "B-CAM16"
    },
    "Bateria": {
        "Codigo": "BT-93075-D",
        "Modelo": "APC"
    }
}

####
GET {{api}}/pc
Content-Type: application/json


####
PUT {{api}}/pc/652e1a49897677ef29e6e73d
Content-Type: application/json

{
    "Codigo": "PC-93075-B",
    "Marca": "DELL",
    "SistemaOperativo": "Windows 10 Pro1234",
    "Hardware": [
        "intel i3 10ma",
        "4GB RAM",
        "1 TB De almacenamiento"
    ],
    "Software": [
        "Office 365",
        "Microsoft Edge",
        "B-View"
    ],
    "Actualizaciones": "Últimas actualizaciones",
    "ConfiguraciónRed": "sin epecificar",
    "Usuarios": "Usuarios: 1",
    "Seguridad": "Contraseñas Baja",
    "RegistroEventos": "Monitoreado",
    "Microscopio": {
        "Codigo": "MC-93075-A",
        "Modelo": "B-CAM16"
    },
    "Bateria": {
        "Codigo": "BT-93075-D",
        "Modelo": "APC"
    }
}

###
DELETE {{api}}/pc/652ebd34e4a91c4f23408b6d
Content-Type: application/json
